plugins {
    id "com.android.application"
}

android {
    namespace "com.futureshijiao.guide.demo"
    compileSdk 36

    defaultConfig {
        applicationId "com.futureshijiao.guide"
        minSdk 21
        targetSdk 36
        versionCode 5
        versionName "1.4.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(":guide-sdk")
}
